# Generated by Django 5.2.8 on 2025-11-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0002_alter_category_options_product_is_sale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_sale',
            new_name='best_offer',
        ),
    ]
