# Generated by Django 5.2.8 on 2025-11-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0003_rename_is_sale_product_best_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
