# Generated by Django 5.2.8 on 2025-12-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0009_alter_customer_email_alter_customer_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
